In [1]:
from sklearn.feature_extraction import DictVectorizer
import csv
from sklearn import preprocessing
from sklearn import tree
from sklearn.externals.six import StringIO

file = open(r'./AllElectronics.csv', 'rt')
reader = csv.reader(file)
headers = next(reader)

print(headers)

['RID\t', 'age', 'income', 'student', 'credit_rating', 'class_buys_computer']


In [2]:
# featureList存放特征属性，转换成多维：举例子“身高属性”的取值“高”“矮”{1.0,0.0}，  
# 若没有序关系，假定有k个属性值，则通常转化成k维向量，  
# 例如属性”瓜类“的取值“西瓜”“南瓜”“黄瓜”可转化为（0,0,1）（0,1,0）（1,0,0）。  
featureList = []  
# labelList存放标签属性  
labelList = []  
  
for row in reader:  
# 读入标签  
    labelList.append(row[len(row)-1])  
    # 添加字典，将属性添加到字典中  
    rowDict = {}
    #将所有特征放入rowDict中
    for i in range(1, len(row)-1):  
        rowDict[headers[i]] = row[i]  
    # 将字典存放到特征属性当中  
    featureList.append(rowDict)  
  
print(featureList)

[{'age': ' youth', 'income': 'high', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'high', 'student': 'no', 'credit_rating': 'excellent'}, {'age': 'middle_aged', 'income': 'high', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'medium', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'low', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'low', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'middle_aged', 'income': 'low', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'youth', 'income': 'medium', 'student': 'no', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'low', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'senior', 'income': 'medium', 'student': 'yes', 'credit_rating': 'fair'}, {'age': 'youth', 'income': 'medium', 'student': 'yes', 'credit_rating': 'excellent'}, {'age': 'middle_aged', 'income': 'medium', 'student': 'no', 'credit_rating': 'excellent'}, {'a

In [3]:
# Vetorize features  
vec = DictVectorizer()  
# python的模块，将字典转换成上面的属性形式  
dummyX = vec.fit_transform(featureList) .toarray()  
  
print("dummyX: " + str(dummyX))  
print(vec.get_feature_names())  
  
print("labelList: " + str(labelList))  

dummyX: [[1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]
['age= youth', 'age=middle_aged', 'age=senior', 'age=youth', 'credit_rating=excellent', 'credit_rating=fair', 'income=high', 'income=low', 'income=medium', 'student=no', 'student=yes']
labelList: ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']


In [4]:
# vectorize class labels  
lb = preprocessing.LabelBinarizer()  
dummyY = lb.fit_transform(labelList)  
print("dummyY: " + str(dummyY)) 

dummyY: [[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [5]:
# Using decision tree for classification  
# clf = tree.DecisionTreeClassifier()  
# sklearn的决策树使用  
clf = tree.DecisionTreeClassifier(criterion='entropy')  
clf = clf.fit(dummyX, dummyY)  
print("clf: " + str(clf))  

clf: DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [6]:
# Visualize model  
# 运用graphviz将决策树写到文档中  
with open("allElectronicInformationGainOri.dot", 'w') as f:  
    f = tree.export_graphviz(clf, feature_names=vec.get_feature_names(), out_file=f) 

# 去除第一行  
oneRowX = dummyX[0, :]  
print("oneRowX: " + str(oneRowX)) 

oneRowX: [1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]


In [7]:
# 修改第一行的数据，然后进行预测  
newRowX = oneRowX  
newRowX[0] = 1  
newRowX[2] = 0  
print("newRowX: " + str(newRowX))
predictedY = clf.predict(newRowX.reshape(1, -1))  
print("predictedY: " + str(predictedY)) 

newRowX: [1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
predictedY: [0]
